spring.profiles.active: local

# JDBC HIKARI
spring:
  datasource:
    platform: postgres
    hakari:
      maximum-pool-size: 4
    url: jdbc:postgresql://210.0.47.232:5432/goldnawa
    username: goldnawa
    password: goldnawa!

# Logging
logging:
  config: classpath:log4j2.xml

# API KEY
api.key: goldnawa!@#

# Caching
spring.cache.jcache.config: classpath:ehcache.xml

# MyBatis
# mapper.xml 위치 지정
mybatis.mapper-locations: mybatis/mapper/**/*.xml
# model 프로퍼티 camel case 설정
mybatis.configuration.map-underscore-to-camel-case: true
# 패키지 명을 생략할 수 있도록 alias 설정
mybatis.type-aliases-package: kr.co.youngyoung.goldnawa.common.domain,kr.co.youngyoung.goldnawa.core.code.domain
# mapper 로그레벨 설정
logging.level.com.atoz_develop.mybatissample.repository: TRACE

---
spring.profiles: local

server:
  port: 8083
---
spring.profiles: dev

server:
  port: 8082
---
spring.profiles: prod

server:
  port: 8081